Feat/sign in UI
nevindra/forum-rakyat pull request #3
Opened 2024-08-27 22:41 UTC by naufaldi

- [x] add font
- [x] add logo and image
- [x] add form components
- [x] align with design
- [x] responsve mobile, tab 
![Screenshot_179](https://github.com/user-attachments/assets/73d0fbda-52bd-4490-be92-f22c69e8a542)

2024-08-27 23:09 UTC, r17x approved these changes
LGTM

2024-08-27 23:15 UTC, r17x commented on src/components/icons/custom.tsx
* Rename `custom.tsx -> social.tsx`

2024-08-27 23:16 UTC, r17x requested changes

2024-08-27 23:16 UTC, r17x commented on src/components/icons/custom.tsx
> +}
Create inline export on each icon

```jsx
const export GoogleIcon = ...
const export SocialNameIcon = ...
```

2024-08-27 23:24 UTC, r17x requested changes

2024-08-27 23:24 UTC, r17x commented on src/components/auth/oauth.tsx
> +import { CustomIcons } from "@/components/icons/custom"
When you change based on this comment https://github.com/nevindra/forum-rakyat/pull/3#discussion_r1733630776.

We can use import 
```jsx
import * as SocialIcon from '@/components/icons/social'
```

2024-08-27 23:24 UTC, r17x commented on src/components/auth/oauth.tsx
> +}
```suggestion
const getIcon = (provider: string) => match(provider)
  .with('google', () => <SocialIcon.GoogleIcon className="h-5 w-5" />)
  .with('facebook', () => <SocialIcon.FacebookIcon className="h-5 w-5" />)
  .with('twitter', () => <SocialIcon.TwitterIcon className="h-5 w-5" />)
  .otherwise(() => null)
```

```js
import { match } from 'ts-pattern'
```

2024-08-27 23:25 UTC, r17x commented
@naufaldi  in your PRs description add `Closes #1` for auto-close your issue when this PR is merged.

2024-08-28 12:37 UTC, naufaldi commented
oke @r17x

2024-08-28 12:59 UTC, r17x approved these changes

2024-08-28 13:01 UTC, merged